"""Architecture diagram command."""

import typer
from pathlib import Path
from rich.console import Console

from devops_ai.diagram import DiagramGenerator
from devops_ai.utils import write_file

console = Console()
app = typer.Typer()


@app.command()
def diagram(
    diagram_type: str = typer.Argument(
        "microservices",
        help="Diagram type (microservices, monolith, serverless, hybrid, pipeline, k8s)",
    ),
    output_file: str = typer.Option(
        "architecture.md", "--output", "-o", help="Output file path"
    ),
):
    """Generate architecture diagrams in Mermaid format."""
    try:
        console.print(f"[cyan]Generating {diagram_type} diagram...[/cyan]")

        generator = DiagramGenerator()

        # Generate based on diagram type
        if diagram_type.lower() == "pipeline":
            content = generator.generate_deployment_pipeline()
            diagram_name = "CI/CD Deployment Pipeline"

        elif diagram_type.lower() == "k8s":
            content = generator.generate_k8s_deployment()
            diagram_name = "Kubernetes Deployment"

        else:
            content = generator.generate_architecture(diagram_type)
            diagram_name = f"{diagram_type.title()} Architecture"

        # Wrap in Markdown
        markdown_content = f"""# {diagram_name}

Generated by DevOps AI Copilot

## Architecture Diagram

```mermaid
{content}
```

## Components

- **Client Layer**: User interfaces and external clients
- **API Layer**: Gateways and load balancers
- **Service Layer**: Business logic and microservices
- **Data Layer**: Databases and caching
- **Integration**: Message queues and external services

## Deployment Notes

- Ensure all security groups and network policies are configured
- Set up monitoring and logging
- Configure backup and disaster recovery
- Implement cost optimization strategies
"""

        output_path = Path(output_file)
        write_file(output_path, markdown_content)

        console.print(
            f"[green]✓[/green] Generated {diagram_type} diagram",
            style="bold",
        )
        console.print(f"[cyan]Output:[/cyan] {output_path.absolute()}")
        console.print(
            f"[yellow]View in:[/yellow] GitHub, GitLab, or any Mermaid-compatible viewer"
        )

    except Exception as e:
        console.print(
            f"[red]✗ Error generating diagram: {e}[/red]",
            style="bold",
        )
        raise typer.Exit(1)
