"""Initialize project command."""

import typer
from pathlib import Path
from rich.console import Console

from devops_ai.utils import ensure_project_dir, save_config

console = Console()
app = typer.Typer()


@app.command()
def init(
    project_name: str = typer.Argument(..., help="Project name"),
    provider: str = typer.Option(
        "aws", "--provider", "-p", help="Cloud provider (aws, gcp, azure)"
    ),
):
    """Initialize a new DevOps project."""
    try:
        project_dir = Path(project_name)
        project_dir.mkdir(exist_ok=True)

        # Create project structure
        for subdir in ["terraform", "k8s", "docker", "github-workflows", "outputs"]:
            ensure_project_dir(project_dir / subdir)

        # Create config file
        config = {
            "project_name": project_name,
            "provider": provider,
            "version": "1.0.0",
        }

        save_config(project_dir / ".devops-ai.json", config)

        # Create README
        readme_content = f"""# {project_name} DevOps

Generated by DevOps AI Copilot

## Project Structure

- `terraform/` - Infrastructure as Code
- `k8s/` - Kubernetes manifests
- `docker/` - Docker configurations
- `github-workflows/` - CI/CD workflows
- `outputs/` - Generated files

## Cloud Provider

Provider: {provider.upper()}

## Getting Started

1. Configure cloud credentials
2. Review generated infrastructure files
3. Deploy using appropriate tools
"""

        with open(project_dir / "README.md", "w") as f:
            f.write(readme_content)

        console.print(
            f"[green]✓[/green] Project '{project_name}' initialized successfully!",
            style="bold",
        )
        console.print(f"[cyan]Location:[/cyan] {project_dir.absolute()}")
        console.print(f"[cyan]Provider:[/cyan] {provider}")

    except Exception as e:
        console.print(f"[red]✗ Error initializing project: {e}[/red]", style="bold")
        raise typer.Exit(1)
